# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Release'

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    steps:
      - uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: 'cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f' # v31
      - run: |
          nix develop --command goreleaser release --clean
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
