# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Release'

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
    steps:
      - uses: 'actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0' # v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: 'cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c' # v31
      - run: |
          nix develop --command goreleaser release --clean
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
